import React from 'react'
import './body.css'
import facebook from './facebook.avif';
import youtube from './youtube.webp';
import whatsapp from './whatsapp.webp';
import instagram from './instagram.jpg';
import tiktok from './tiktok.jpg';


const body = () => {
  return (
    <div class="main-div">
      <div>
      <h1>1) FACEBOOK</h1>
           <img class="body-images"  alt="logo"src={facebook} />

           <p>Let's start with the obvious choices. For all its faults (and there are a lot of them), Facebook is still comfortably the most popular social network in the world.</p>
            <p>With more than 2.95 billion users, it's the place to go if you want to easily connect with most of the people from your current or former life. Facebook Marketplace has also become one of the most popular ways to buy and sell items locally and is now more popular than Craigslist.</p>
      </div>
      <br/>
      <div>
      <h1> 2) YOUTUBE</h1>
            <img class="body-images"  alt="logo"src={youtube} />
                  <p>YouTube is an American online video sharing and social media platform headquartered in San Bruno, California, United States. Accessible worldwide, it was launched on February 14, 2005, by Steve Chen, Chad Hurley, and Jawed Karim. It is owned by Google and is the second most visited website in the world, after Google Search. YouTube has more than 2.5 billion monthly users, who collectively watch more than one billion hours of videos every day.[9] As of May 2019, videos were being uploaded to the platform at a rate of more than 500 hours of content per minute.</p>

<p>In October 2006, YouTube was bought by Google for $1.65 billion.Google's ownership of YouTube expanded the site's business model, expanding from generating revenue from advertisements alone to offering paid content such as movies and exclusive content produced by YouTube. It also offers YouTube Premium, a paid subscription option for watching content without ads. YouTube also approved creators to participate in Google's AdSense program, which seeks to generate more revenue for both parties. In 2021, YouTube's annual advertising revenue increased to $28.8 billion, an increase in revenue of 9 billion from the previous year.YouTube reported revenue of $29.2 billion in 2022.</p>

<p>Since its purchase by Google, YouTube has expanded beyond the core website into mobile apps, network television, and the ability to link with other platforms. Video categories on YouTube include music videos, video clips, news, short films, feature films, songs, documentaries, movie trailers, teasers, live streams, vlogs, and more. Most content is generated by individuals, including collaborations between YouTubers and corporate sponsors. Established media corporations such as Disney, Paramount, NBCUniversal, and Warner Bros. Discovery have also created and expanded their corporate YouTube channels to advertise to a greater audience.</p>

YouTube has had unprecedented social impact, influencing popular culture, internet trends, and creating multimillionaire celebrities. Despite its growth and success, it has been widely criticized for allegedly facilitating the spread of misinformation and the sharing of copyrighted content, routinely violating its users' privacy, enabling censorship, and endangering child safety and wellbeing, and for its inconsistent or incorrect implementation of platform guidelines.

      </div>
      <br/>
      <div>
      <h1> 3) WHATSAPP</h1>
      <img class="body-images"  alt="logo"src={whatsapp} />

               <p> WhatsApp (officially WhatsApp Messenger) is a freeware, cross-platform, centralized instant messaging (IM) and voice-over-IP (VoIP) service owned by United States tech conglomerate Meta Platforms.[14] It allows users to send text, voice messages and video messages,make voice and video calls, and share images, documents, user locations, and other content.WhatsApp's client application runs on mobile devices, and can be accessed from computers.The service requires a cellular mobile telephone number to sign up.[19] In January 2018, WhatsApp released a standalone business app called WhatsApp Business which can communicate with the standard WhatsApp client.</p>

<p> The service was created by WhatsApp Inc. of Mountain View, California, which was acquired by Facebook in February 2014 for approximately US$19.3 billion.It became the world's most popular messaging application by 2015,and had more than 2 billion users worldwide by February 2020.By 2016, it had become the primary means of Internet communication in regions including Latin America, the Indian subcontinent, and large parts of Europe and Africa.</p>
      </div>
      <br/>
      <div>
      <h1> 4) INSTAGRAM</h1>
      <img class="body-images"  alt="logo"src={instagram} />
             <p>Instagram (sometimes shortened to Insta or IG) is an online photo and video sharing social networking service. It allows users to take pictures and videos, add digital filters to them and share them to their followers. They can then share them on a variety of social networking services, such as Facebook, Twitter, Tumblr, and Flickr.</p>

<p>Until 2015,Instagram confined photos to a square shape, similar to Kodak Instamatic and Polaroid images. This was different than the 4:3 aspect ratio typically used by digital cameras. Users were able to share very short videos.[8] In 2017, the length limit was raised to ten minutes.</p>

<p>Instagram was created by Kevin Systrom and Mike Krieger. When Kevin Systrom and Mike Krieger talked to famous NY Photographer Peter Parker, a photographer for the Daily Bugle, Systrom and Krieger were inspired to make an app just for photography. It was released on October 6, 2010.</p>

      </div>
      <br/>
      <div>
      <h1> 5) TIKTOK</h1>
      <img class="body-images"  alt="logo"src={tiktok} />

                  <p>TikTok, whose mainland Chinese counterpart is Douyin (Chinese: 抖音; pinyin: Dǒuyīn), is a short-form video hosting service owned by ByteDance.It hosts user-submitted videos, which can range in duration from 3 seconds to 10 minutes.Since their launches, TikTok and Douyin have gained global popularity.In October 2020, TikTok surpassed 2 billion mobile downloads worldwide.Morning Consult named TikTok the third-fastest growing infotech brand of 2020, after Zoom and Peacock.Cloudflare ranked TikTok the most popular website of 2021, surpassing Google.</p>

<p>Corporate structure
ByteDance, based in Beijing, and its subsidiary TikTok Ltd were incorporated in the Cayman Islands. ByteDance is owned by its founders and Chinese investors (20%), other global investors (60%), and employees (20%).TikTok Ltd owns four entities that are based respectively in the United States, Australia (which also runs the New Zealand business), United Kingdom (also owns subsidiaries in the European Union), and Singapore (owns operations in Southeast Asia and India).</p>

<p>In April 2021, a state-owned enterprise owned by the Cyberspace Administration of China and China Media Group, the China Internet Investment Fund, purchased a 1% stake in ByteDance's main Chinese entity.The Economist, Reuters, and Financial Times have described the Chinese government's stake as a golden share investment.As of 2023, TikTok's upper-level management is increasingly drawn from ByteDance executives from China.</p>
      </div>
    </div>
  )
}

export default body